(function(){
const KEY='freshcartAdminConfig', ORIGINAL='freshcartOriginalConfig';
const clone=x=>JSON.parse(JSON.stringify(x||{}));
function merge(base,saved){base=clone(base);saved=saved||{};const mergeById=(baseArr,savedArr)=>{if(!Array.isArray(savedArr)||!savedArr.length)return baseArr||[];let seen=new Set(savedArr.map(x=>x&&x.id).filter(Boolean));return [...savedArr,...(baseArr||[]).filter(x=>x&&x.id&&!seen.has(x.id))]};return {...base,...saved,business:{...(base.business||{}),...(saved.business||{})},admin:{...(base.admin||{}),...(saved.admin||{})},socials:saved.socials||base.socials||[],categories:mergeById(base.categories,saved.categories),products:mergeById(base.products,saved.products),deliveryOptions:saved.deliveryOptions||base.deliveryOptions||[],servicePromises:saved.servicePromises||base.servicePromises||[]}}
function cfg(){try{return window.FRESHCART_ACTIVE_CONFIG||merge(window.FRESHCART_DEFAULTS||{},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return window.FRESHCART_ACTIVE_CONFIG||window.FRESHCART_DEFAULTS||{}}}
function save(c){localStorage.setItem(KEY,JSON.stringify(c));window.dispatchEvent(new Event('freshcart-config-updated'))}
function money(n){return 'RWF '+Number(n||0).toLocaleString()}function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function page(){return(location.pathname.split('/').pop()||'index.html').toLowerCase()}
function css(){if(document.getElementById('fc-live-css'))return;let st=document.createElement('style');st.id='fc-live-css';st.textContent=`.fc-fixed-home,.home-btn{position:fixed!important;top:12px!important;left:12px!important;z-index:9999!important;background:#555!important;color:#fff!important;border-radius:7px!important;padding:9px 16px!important;text-decoration:none!important;font-weight:700!important;box-shadow:0 8px 18px rgba(0,0,0,.25)!important}.fc-fixed-home:hover,.home-btn:hover{background:#111!important}.filter-bar{display:none!important}#delivery-option{appearance:none;-webkit-appearance:none;background:#fff url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 20 20'%3E%3Cpath fill='%23ff4500' d='M5.5 7.5 10 12l4.5-4.5z'/%3E%3C/svg%3E") no-repeat right 14px center!important;border:2px solid #ff8a5b!important;border-radius:14px!important;padding:13px 44px 13px 14px!important;font-weight:700!important;color:#222!important;box-shadow:0 8px 22px rgba(255,69,0,.13)!important;transition:.25s!important}#delivery-option:focus{outline:none!important;border-color:#ff4500!important;box-shadow:0 0 0 4px rgba(255,69,0,.16)!important}.product-card{transition:transform .3s ease,box-shadow .3s ease!important}.product-card:hover{transform:translateY(-5px) scale(1.02)!important}.fc-print-only{display:none}`;document.head.appendChild(st)}
function getCat(c){let pg=page(), catId=new URLSearchParams(location.search).get('cat');return (c.categories||[]).find(x=>(x.page||'').toLowerCase()===pg||(catId&&x.id===catId))}
function productHTML(p){let name=p.displayName||p.name||'Product',unit=p.unit||'unit',price=Number(p.price||0),img=p.image||'img/category-header.webp',desc=p.description||'Fresh product available for delivery.';return `<div class="product-card" data-fc-id="${esc(p.id)}"><img src="${esc(img)}" alt="${esc(name)}"><h3>${esc(name)}</h3><p>${esc(desc)}</p><p class="price">${money(price)} / ${esc(unit)}</p><button onclick='addToCart(${JSON.stringify(name)},${price},${JSON.stringify(unit)})'>Add to Cart</button></div>`}
function applyCategoryHeader(c){let cat=getCat(c);if(!cat)return;document.querySelectorAll('header').forEach(h=>{h.style.backgroundImage=`url('${cat.headerImage||cat.image||'img/category-header.webp'}')`;let h1=h.querySelector('h1');if(h1)h1.textContent=cat.name||'Products';let h2=h.querySelector('h2');if(h2)h2.textContent=cat.description||'';});document.querySelectorAll('[data-fc-category-title]').forEach(e=>e.textContent=cat.name||'Products');document.querySelectorAll('[data-fc-category-description]').forEach(e=>e.textContent=cat.description||'Browse fresh products and order for delivery.');document.title=(cat.name||'Products')+' | Kigali FreshCart'}
function applyProducts(c){let cat=getCat(c);if(cat){let cont=document.querySelector('.products-container');if(cont){let ps=(c.products||[]).filter(p=>p.categoryId===cat.id||(p.page||'').toLowerCase()===(cat.page||'').toLowerCase());if(cat.id==='fruits'){const fruitPriority={'fruits-bananas-kamara-dozen':0,'fruits-bananas-dozen':1};ps=ps.map((p,i)=>({p,i})).sort((a,b)=>(fruitPriority[a.p.id]??(a.i+10))-(fruitPriority[b.p.id]??(b.i+10))).map(x=>x.p)}cont.innerHTML=ps.map(productHTML).join('')||'<p>No products available yet.</p>';}return}let m={};(c.products||[]).forEach(p=>m[p.id]=p);document.querySelectorAll('.product-card[data-fc-id]').forEach(card=>{let p=m[card.dataset.fcId];if(!p)return;let name=p.displayName||p.name,unit=p.unit||'unit',price=Number(p.price||0),h=card.querySelector('h3'),pr=card.querySelector('.price'),btn=card.querySelector('button[onclick*=addToCart]'),img=card.querySelector('img'),desc=[...card.querySelectorAll('p')].find(x=>!x.classList.contains('price'));if(h)h.textContent=name;if(desc&&p.description)desc.textContent=p.description;if(img&&p.image){img.src=p.image;img.alt=name}if(pr)pr.textContent=money(price)+' / '+unit;if(btn)btn.setAttribute('onclick','addToCart('+JSON.stringify(name)+','+price+','+JSON.stringify(unit)+')')})}
function applyCategories(c){if(page()!=='index.html')return;let w=document.querySelector('.categories');if(!w)return;w.innerHTML=(c.categories||[]).map(cat=>{let href=cat.page||('category.html?cat='+encodeURIComponent(cat.id));return `<div class="category" data-name="${esc(cat.name)}"><img src="${esc(cat.image||'img/category-header.webp')}" alt="${esc(cat.name)}"><h3>${esc(cat.name)}</h3><p>${esc(cat.description||'Fresh products delivered to your door.')}</p><button onclick="window.location.href='${esc(href)}'">Browse Products</button></div>`}).join('')}
function applyDelivery(c){document.querySelectorAll('select#delivery-option').forEach(sel=>{let cur=sel.value;sel.innerHTML='';(c.deliveryOptions||[]).forEach(o=>{let opt=document.createElement('option');opt.value=Number(o.fee||0);opt.textContent=o.label||money(o.fee);sel.appendChild(opt)});if([...sel.options].some(o=>o.value===cur))sel.value=cur})}
function applyContact(c){let b=c.business||{};document.querySelectorAll('a[href*=wa\.me],a[href*=api\.whatsapp\.com]').forEach(a=>{if(b.whatsappNumber)a.href='https://wa.me/'+String(b.whatsappNumber).replace(/\D/g,'')});document.querySelectorAll('a[href^="mailto:"]').forEach(a=>{if(b.email)a.href='mailto:'+b.email});document.querySelectorAll('.fc-admin-link').forEach(a=>a.remove())}
function applyFooter(c){let about=(c.business||{}).aboutDescription||'';document.querySelectorAll('footer p').forEach(p=>{let h=p.closest('div')?.querySelector('h3');if(h&&/About FreshCart/i.test(h.textContent))p.textContent=about});let html=(c.socials||[]).map(s=>`<div><a href="${esc(s.link||'#')}" target="_blank" rel="noopener"><img src="${esc(s.icon||'img/share-icon.webp')}" alt="${esc(s.name||'Social')}"></a><p>${esc(s.name||'Social')}</p></div>`).join('');document.querySelectorAll('.social-media').forEach(w=>{w.innerHTML=html});document.querySelectorAll('.social-links').forEach(w=>{w.innerHTML=(c.socials||[]).map(s=>`<a href="${esc(s.link||'#')}" target="_blank" rel="noopener">${esc(s.name||'Social')}</a>`).join('')})}
function applyServices(c){let services=c.servicePromises||[];if(!services.length)return;let map={};services.forEach(x=>{if(x&&x.id)map[x.id]=x});document.querySelectorAll('.info-banner .info-item, .services .service, .service, .feature-card').forEach(card=>{let h=card.querySelector('h3');if(!h)return;let key=h.textContent.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let svc=map[key]||services.find(x=>(x.title||'').toLowerCase()===h.textContent.trim().toLowerCase());if(!svc)return;h.textContent=svc.title||h.textContent;let p=card.querySelector('p');if(p&&svc.text)p.textContent=svc.text;let img=card.querySelector('img');if(img&&svc.icon){img.src=svc.icon;img.alt=(svc.title||'Service')+' Icon'}})}
function applyCartNote(c){if(page()!=='cart.html')return;let note=(c.business||{}).cartPaymentNote;if(!note)return;let box=document.querySelector('.note-box');if(box){box.textContent=note;return}let btn=document.querySelector('.checkout-btn');if(btn){let p=btn.previousElementSibling;if(p)p.textContent=note}}

function overrideCartCheckout(c){if(page()!=='cart.html')return;window.proceedToPayment=function(){let cart=JSON.parse(localStorage.getItem('cart'))||[];if(!cart.length){alert('Your cart is empty!');return}let deliveryFee=parseInt(document.getElementById('delivery-option')?.value||'0')||0;if(deliveryFee===0){alert('Please select a delivery option.');return}let name=document.getElementById('name')?.value||document.getElementById('customer-name')?.value||'';let phone=document.getElementById('phone')?.value||document.getElementById('customer-phone')?.value||'';let location=document.getElementById('location')?.value||document.getElementById('customer-location')?.value||'';let subtotal=cart.reduce((sum,item)=>sum+Number(item.price||0)*Number(item.quantity||1),0);let msg='🛒 *Kigali FreshCart Order*%0A%0A';if(name)msg+='👤 *Name:* '+encodeURIComponent(name)+'%0A';if(phone)msg+='📞 *Phone:* '+encodeURIComponent(phone)+'%0A';if(location)msg+='📍 *Location:* '+encodeURIComponent(location)+'%0A';msg+='%0A*Order Summary:*%0A';cart.forEach(item=>{let nm=item.productName||item.name||'Product', qty=Number(item.quantity||1), price=Number(item.price||0), unit=item.unit||'unit';msg+='🔹 '+encodeURIComponent(nm)+' ('+encodeURIComponent(unit)+') - '+qty+' x '+money(price)+' = '+money(price*qty)+'%0A'});msg+='%0A🚚 *Delivery Fee:* '+money(deliveryFee);msg+='%0A💰 *Grand Total:* '+money(subtotal+deliveryFee);msg+='%0A%0A📲 Click send to confirm your order.';let num=String((c.business||{}).whatsappNumber||'250727725180').replace(/\D/g,'');window.open('https://wa.me/'+num+'?text='+msg,'_blank')}}
function run(){css();let c=cfg();applyCategories(c);applyCategoryHeader(c);applyProducts(c);applyDelivery(c);applyContact(c);applyFooter(c);applyServices(c);applyCartNote(c);overrideCartCheckout(c);if(!window.__fcCloudLoaded&&window.FreshCartCloud&&window.FreshCartCloud.isConfigured()){window.__fcCloudLoaded=true;window.FreshCartCloud.load().then(remote=>{if(remote){localStorage.setItem(KEY,JSON.stringify(remote));window.FRESHCART_ACTIVE_CONFIG=merge(window.FRESHCART_DEFAULTS||{},remote);run();}}).catch(err=>console.warn('FreshCart cloud load skipped:',err));}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
window.addEventListener('storage',e=>{if(e.key===KEY)run()});window.addEventListener('freshcart-config-updated',run);
window.FreshCartAdmin={getConfig:cfg,saveConfig:save,reset:()=>localStorage.removeItem(KEY),saveAsOriginal:()=>localStorage.setItem(ORIGINAL,localStorage.getItem(KEY)||JSON.stringify(cfg()))};
})();
